//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_first_app
{
    using System;
    using System.Collections.Generic;
    
    public class Training
    {
        public int id { get; set; }
        public TimeSpan training_time { get; set; }
        public int training_group_id { get; set; }
        public int trainer { get; set; }
        public Training(int id, TimeSpan training_time, int training_group_id, int trainer)
        {
            this.id = id;
            this.training_time = training_time;
            this.training_group_id = training_group_id;
            this.trainer = trainer;
        }

        public Training()
        {
        }
    }
}
