//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_first_entity_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
        }

        public Member(int id, string first_name, string last_name, int? training_group_id)
        {
            this.id = id;
            this.first_name = first_name;
            this.last_name = last_name;
            this.training_group_id = training_group_id;
        }

        public int id { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public Nullable<int> training_group_id { get; set; }
    }
}
