//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace database_first_entity_app
{
    using System;
    using System.Collections.Generic;
    
    public partial class TrainingGroup
    {
        public TrainingGroup()
        {
        }

        public TrainingGroup(int id, int? trainer_id)
        {
            this.id = id;
            this.trainer_id = trainer_id;
        }

        public int id { get; set; }
        public Nullable<int> trainer_id { get; set; }
    }
}
